In [1]:
import numpy as np
import argparse
import cv2 as cv
import subprocess
import time
import os
from yolo_utils import infer_image, show_image

In [2]:
FLAGS = []

if __name__ == '__main__':
    parser = argparse.ArgumentParser()

    parser.add_argument('-w', '--weights',
        default='./weights/yolov3.weights')

    parser.add_argument('-cfg', '--config',
        default='./cfg/yolov3.cfg')

    parser.add_argument('-l', '--labels',
        default='./data/cocomod.names')

    parser.add_argument('-c', '--confidence',
        default=0.5)

    parser.add_argument('-th', '--threshold',
        default=0.3)

    parser.add_argument('--download-model',
        default=False)

    parser.add_argument('-t', '--show-time',
        default=False)

    FLAGS, unparsed = parser.parse_known_args()



In [3]:

# Get the labels
labels = open(FLAGS.labels).read().strip().split('\n')
print(labels)


['person']


In [4]:

# Intializing colors to represent each label uniquely
colors = np.random.randint(0, 255, size=(len(labels), 3), dtype='uint8')
print(colors)#On RGB Format


[[ 85 113 140]]


In [5]:

# Load the weights and configutation to form the pretrained YOLOv3 model
net = cv.dnn.readNetFromDarknet(FLAGS.config, FLAGS.weights)
print(net)


<dnn_Net 000001FB29813ED0>


In [6]:

    # Get the output layer names of the model
layer_names = net.getLayerNames()
layer_names = [layer_names[i - 1] for i in net.getUnconnectedOutLayers()]


In [7]:
# Infer real-time on webcam
#Numpy is used for all things "numbers and Python." We are mainly making use of Numpy's array functionality.
#*OpenCV reads colors as BGR (Blue Green Red), where most computer applications read as RGB (Red Green Blue).
#
#
#
#



vid = cv.VideoCapture(0)
print(vid)


<VideoCapture 000001FB2984C130>


In [9]:
count=0

while True:
            _, frame = vid.read()
            
            height, width = frame.shape[:2]
            if count == 0:
                frame, boxes, confidences, classids, idxs = infer_image(net, layer_names, \
                                    height, width, frame, colors, labels, FLAGS)
                count += 1
               
            else:
                frame, boxes, confidences, classids, idxs = infer_image(net, layer_names, \
                                    height, width, frame, colors, labels, FLAGS, boxes, confidences, classids, idxs, infer=False)
                count = (count + 1) % 6
            

            cv.imshow('webcam', frame)
            print(frame)

            if cv.waitKey(1) & 0xFF == ord('q'):
                break
#print("No of Persons"+ str(count))            
vid.release()
cv.destroyAllWindows()

[[[152 160 152]
  [155 164 155]
  [153 161 151]
  ...
  [186 216 228]
  [184 213 230]
  [183 213 232]]

 [[149 159 149]
  [151 162 150]
  [151 162 150]
  ...
  [185 215 227]
  [183 214 229]
  [182 213 231]]

 [[148 162 148]
  [146 160 145]
  [147 161 146]
  ...
  [186 215 225]
  [186 217 229]
  [182 215 228]]

 ...

 [[ 96  63  67]
  [ 91  60  63]
  [101  71  73]
  ...
  [136 116 118]
  [135 116 116]
  [141 122 122]]

 [[ 97  52  61]
  [ 95  52  60]
  [104  65  71]
  ...
  [128 110 110]
  [128 110 109]
  [128 110 109]]

 [[102  51  62]
  [ 96  46  57]
  [ 96  50  59]
  ...
  [125 107 106]
  [129 111 110]
  [125 107 106]]]
[[[101 126 116]
  [106 130 119]
  [107 129 117]
  ...
  [155 171 171]
  [156 173 173]
  [157 174 174]]

 [[104 126 117]
  [107 129 118]
  [111 131 119]
  ...
  [155 171 170]
  [157 173 172]
  [158 174 173]]

 [[109 128 119]
  [109 128 119]
  [115 132 122]
  ...
  [159 174 173]
  [162 176 175]
  [165 178 177]]

 ...

 [[ 64  47  44]
  [ 62  45  42]
  [ 59  42  39]
  ..

KeyboardInterrupt: 